# -*- coding: utf-8 -*-
"""myChatBot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e4XcEV1H3OxQFOC1mEFL6nAo2TH2M7SJ
"""

import os
import streamlit as st
from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain_core.output_parsers.string import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate

# Load environment variables
load_dotenv()
os.environ["GROQ_API_KEY"] = "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"

# Set up system prompt
system_prompt = """
You are a helpful assistant.
When the conversation start, you should say "Welcome to Hayet".
You have to provide detailed answers to the user's queries.
When the conversation ends, you should say "Have a nice day".
"""
prompt = ChatPromptTemplate.from_messages(
    [("system", system_prompt), ("human", "{input}")]
)
llm = ChatGroq(temperature=1, model="llama3-8b-8192")
chain = prompt | llm | StrOutputParser()

# Streamlit App Layout
st.set_page_config(page_title="Chat with Hayet", page_icon="💬", layout="wide")

# Custom CSS for background, font, and button styles
st.markdown("""
    <style>
    body {
        background-color: #f0f4c3;
        color: #2e7d32;
        font-family: 'Arial', sans-serif;
    }
    .stButton button {
        background-color: #2e7d32;
        color: white;
        border-radius: 10px;
        width: 200px;
        height: 50px;
    }
    .stTextInput {
        font-size: 20px;
    }
    .stAlert {
        font-size: 18px;
    }
    </style>
""", unsafe_allow_html=True)

# Main app content
st.title("💬 Chat with Hayet")
st.write("Ask your question below:")

# Input field for user question
user_question = st.text_input("What do you want to ask?", placeholder="Type your question here...")

# Add a decorative separator line
st.markdown("***")

# Handle user input and display response
if st.button("Ask"):
    if user_question:

        response = chain.invoke({"input": user_question})
        st.success(response)
    else:
        st.warning("Please enter a question.")